version: '3.8'
services:
  frontend:
    image: dreammf/dream.mf-frontend:0.9.0
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=https://localhost:5001
      - AUTH_AUTHORITY=http://localhost:5000
      - AUTH_CLIENT_ID=DreamMF-Web-01202025

  backend:
    image: dreammf/dream.mf-backend:0.9.0
    build:
      context: .
      target: final
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Dr34m0120225
    volumes:
      - ~/.aspnet/https:/https:ro
