version: '3.8'
services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:5000

  backend:
    build:
      context: .
      target: final
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword
    volumes:
      - ~/.aspnet/https:/https:ro
