version: '3.8'
services:
  
  frontend:
    image: dreammf/ros-frontend:0.14.0
    build:
      context: .
      target: frontend-server
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        BACKEND_URL: https://localhost:4001
        AUTH_AUTHORITY: https://localhost:4001
        AUTH_CLIENT_ID: DreamMF-Web-01202025
    ports:
      - "3000:3000"

  backend:
    image: dreammf/ros-backend:0.14.0
    build:
      context: .
      target: final
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    volumes:
      - ~/.aspnet/https:/https:ro
      - dream-ros-db-data:/app/remote_orchestration.db

volumes:
  dream-ros-db-data:
