version: '3.8'

services:
  frontend:
    image: dreammf/ros-frontend:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        BACKEND_URL: https://localhost:4001
        AUTH_AUTHORITY: https://localhost:4001
        AUTH_CLIENT_ID: DreamMF-Web-01202025
    ports:
      - "3000:3000"

  backend:
    image: dreammf/ros-backend:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    volumes:
      # This is a bind mount for HTTPS certs on the host
      - ~/.aspnet/https:/https:ro
      # Named volume is now mounted on /app/data (a directory)
      - dream-ros-db-data:/app/data

volumes:
  dream-ros-db-data: