version: '3.8'
services:
  
  frontend:
    image: dreammf/ros-frontend:0.9.12
    build:
      context: .
      target: frontend-server
      args:
        BACKEND_URL: https://localhost:5001
        AUTH_AUTHORITY: https://localhost:5001
        AUTH_CLIENT_ID: DreamMF-Web-01202025
    ports:
      - "3000:80"

  backend:
    image: dreammf/ros-backend:0.9.12
    build:
      context: .
      target: final
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
    volumes:
      - ~/.aspnet/https:/https:ro
