name: Docker Compose Build and Deploy

env:
  VERSION: 1.2.1

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            dreammf/ros-frontend:${{ env.VERSION }}-${{ matrix.arch }}
            dreammf/ros-frontend:latest-${{ matrix.arch }}
            dreammf/ros-backend:${{ env.VERSION }}-${{ matrix.arch }}
            dreammf/ros-backend:latest-${{ matrix.arch }}

      - name: Build and push latest amd64 images
        if: matrix.arch == 'amd64'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            dreammf/ros-frontend:latest
            dreammf/ros-backend:latest

      - name: Ensure Docker Compose plugin is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli-plugin-compose

      - name: Deploy with Docker Compose
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
